function trinit_plants()
{
	if (!setup.trPlants)
	{
		setup.trPlants = [
				{
					name: "red_rose",
					singular: "red_rose",
					plural: "red roses",
					name_ko: "붉은 장미",
					post: 1,
					unit_ko: "송이",
					unit_post: 1,
				},

				{
					name: "white_rose",
					singular: "white_rose",
					plural: "white roses",
					name_ko: "백장미",
					post: 1,
					unit_ko: "송이",
					unit_post: 1,
				},

				{
					name: "orchid",
					singular: "orchid",
					plural: "orchids",
					name_ko: "난초",
					post: 1,
					unit_ko: "촉",
					unit_post: 0,
				},

				{
					name: "daisy",
					singular: "daisy",
					plural: "daisies",
					name_ko: "데이지",
					post: 1,
					unit_ko: "송이",
					unit_post: 1,
				},

				{
					name: "tulip",
					singular: "tulip",
					plural: "tulips",
					name_ko: "튤립",
					post: 0,
					unit_ko: "송이",
					unit_post: 1,
				},

				{
					name: "lotus",
					singular: "lotus",
					plural: "lotus",
					name_ko: "연꽃",
					post: 0,
					unit_ko: "송이",
					unit_post: 1,
				},

				{
					name: "lily",
					singular: "lily",
					plural: "lilies",
					name_ko: "백합",
					post: 0,
					unit_ko: "송이",
					unit_post: 1,
				},

				{
					name: "poppy",
					singular: "poppy",
					plural: "poppies",
					name_ko: "양귀비",
					post: 1,
					unit_ko: "송이",
					unit_post: 1,
				},
				
				{
					name: "apple",
					singular: "apple",
					plural: "apples",
					name_ko: "사과",
					post: 1,
					unit_ko: "개",
					unit_post: 1,
				},

				{
					name: "orange",
					singular: "orange",
					plural: "oranges",
					name_ko: "오렌지",
					post: 1,
					unit_ko: "개",
					unit_post: 1,
				},

				{
					name: "banana",
					singular: "banana",
					plural: "bananas",
					name_ko: "바나나",
					post: 1,
					unit_ko: "송이",
					unit_post: 1,
				},

				{
					name: "lemon",
					singular: "lemon",
					plural: "lemons",
					name_ko: "레몬",
					post: 0,
					unit_ko: "개",
					unit_post: 1,
				},

				{
					name: "blood_lemon",
					singular: "blood_lemon",
					plural: "blood lemons",
					name_ko: "블러드 레몬",
					post: 0,
					unit_ko: "개",
					unit_post: 1,
				},

				{
					name: "pear",
					singular: "pear",
					plural: "pears",
					name_ko: "배",
					post: 1,
					unit_ko: "개",
					unit_post: 1,
				},

				{
					name: "strawberry",
					singular: "strawberry",
					plural: "strawberries",
					name_ko: "딸기",
					post: 1,
					unit_ko: "개",
					unit_post: 1,
				},

				{
					name: "peach",
					singular: "peach",
					plural: "peaches",
					name_ko: "복숭아",
					post: 1,
					unit_ko: "개",
					unit_post: 1,
				},

				{
					name: "plum",
					singular: "plum",
					plural: "plums",
					name_ko: "자두",
					post: 1,
					unit_ko: "개",
					unit_post: 1,
				},

				{
					name: "mushroom",
					singular: "mushroom",
					plural: "mushrooms",
					name_ko: "버섯",
					post: 0,
					unit_ko: "송이",
					unit_post: 1,
				},

				{
					name: "wolfshroom",
					singular: "wolfshroom",
					plural: "wolfshrooms",
					name_ko: "늑대 버섯",
					post: 0,
					unit_ko: "송이",
					unit_post: 1,
				},

				{
					name: "wild_honeycomb",
					singular: "wild_honeycomb",
					plural: "wild honeycombs",
					name_ko: "야생 벌집",
					post: 0,
					unit_ko: "개",
					unit_post: 1,
				},

				{
					name: "wild_carrot",
					singular: "wild_carrot",
					plural: "carrots",
					name_ko: "야생 당근",
					post: 0,
					unit_ko: "개",
					unit_post: 1,
				},

				{
					name: "onion",
					singular: "onion",
					plural: "onions",
					name_ko: "양파",
					post: 1,
					unit_ko: "개",
					unit_post: 1,
				},

				{
					name: "garlic_bulb",
					singular: "garlic_bulb",
					plural: "garlic bulbs",
					name_ko: "마늘",
					post: 2,
					unit_ko: "통",
					unit_post: 0,
				},

				{
					name: "potato",
					singular: "potato",
					plural: "potatoes",
					name_ko: "감자",
					post: 1,
					unit_ko: "개",
					unit_post: 1,
				},

				{
					name: "strange_flower",
					singular: "strange_flower",
					plural: "strange flowers",
					name_ko: "이상한 꽃",
					post: 0,
					unit_ko: "송이",
					unit_post: 1,
				},

				{
					name: "truffle",
					singular: "truffle",
					plural: "truffles",
					name_ko: "송로버섯",
					post: 0,
					unit_ko: "송이",
					unit_post: 1,
				},

				{
					name: "bottle_of_milk",
					singular: "bottle_of_milk",
					plural: "bottles of milk",
					name_ko: "우유를 넣은 병",
					post: 0,
					unit_ko: "병",
					unit_post: 0,
				},

				{
					name: "egg",
					singular: "egg",
					plural: "eggs",
					name_ko: "계란",
					post: 0,
					unit_ko: "개",
					unit_post: 1,
				},

				{
					name: "chicken_egg",
					singular: "chicken_egg",
					plural: "chicken eggs",
					name_ko: "계란",
					post: 0,
					unit_ko: "개",
					unit_post: 1,
				},

				{
					name: "bottle_of_breast_milk",
					singular: "bottle_of_breast_milk",
					plural: "bottles of breast milk",
					name_ko: "모유를 넣은 병",
					post: 0,
					unit_ko: "병",
					unit_post: 0,
				},

				{
					name: "bottle_of_semen",
					singular: "bottle_of_semen",
					plural: "bottles of semen",
					name_ko: "정액을 넣은 병",
					post: 0,
					unit_ko: "병",
					unit_post: 0,
				},

				{
					name: "cabbage",
					singular: "cabbage",
					plural: "cabbages",
					name_ko: "양배추",
					post: 1,
					unit_ko: "포기",
					unit_post: 1,
				},

				{
					name: "turnip",
					singular: "turnip",
					plural: "turnips",
					name_ko: "순무",
					post: 1,
					unit_ko: "개",
					unit_post: 1,
				},

				{
					name: "broccoli",
					singular: "broccoli",
					plural: "broccoli",
					name_ko: "브로콜리",
					post: 1,
					unit_ko: "개",
					unit_post: 1,
				},

				{
					name: "ghostshroom",
					singular: "ghostshroom",
					plural: "ghostshrooms",
					name_ko: "유령버섯",
					post: 0,
					unit_ko: "송이",
					unit_post: 1,
				},

				{
					name: "blackberry",
					singular: "blackberry",
					plural: "blackberries",
					name_ko: "블랙베리",
					post: 1,
					unit_ko: "개",
					unit_post: 1,
				},

				{
					name: "carnation",
					singular: "carnation",
					plural: "carnations",
					name_ko: "카네이션",
					post: 0,
					unit_ko: "송이",
					unit_post: 1,
				},

				{
					name: "bird_egg",
					singular: "bird_egg",
					plural: "bird eggs",
					name_ko: "새 알",
					post: 2,
					unit_ko: "개",
					unit_post: 1,
				},

				{
					name: "baby_bottle_of_breast_milk",
					singular: "baby bottle of breast milk",
					plural: "baby bottles of breast milk",
					name_ko: "모유를 넣은 젖병",
					post: 0,
					unit_ko: "병",
					unit_post: 0,
				},

				{
					name: "plumeria",
					singular: "plumeria",
					plural: "plumerias",
					name_ko: "플루메리아",
					post: 1,
					unit_ko: "송이",
					unit_post: 1,
				},

				{
					name: "oyster_pearl",
					singular: "oyster pearl",
					plural: "oyster pearls",
					name_ko: "진주",
					post: 1,
					unit_ko: "개",
					unit_post: 1,
				},

				{
					name: "bread",
					singular: "piece of bread",
					plural: "pieces of bread",
					name_ko: "빵",
					post: 0,
					unit_ko: "조각",
					unit_post: 0,
				},
				{
					name: "flour",
					singular: "spoonful of flour",
					plural: "spoonfuls of flour",
					name_ko: "밀가루",
					post: 1,
					unit_ko: "스푼",
					unit_post: 0,
				},
				{
					name: "salt",
					singular: "pinch of salt",
					plural: "pinches of salt",
					name_ko: "소금",
					post: 0,
					unit_ko: "꼬집",
					unit_post: 0,
				},
				{
					name: "vegetable_oil",
					singular: "spoonful of vegetable oil",
					plural: "spoonfuls of vegetable oil",
					name_ko: "식물성 기름",
					post: 0,
					unit_ko: "스푼",
					unit_post: 0,
				},
				{
					name: "pizza",
					singular: "pizza",
					plural: "pizzas",
					name_ko: "피자",
					post: 1,
					unit_ko: "판",
					unit_post: 0,
				},
				{
					name: "tomato",
					singular: "tomato",
					plural: "tomatoes",
					name_ko: "토마토",
					post: 1,
					unit_ko: "개",
					unit_post: 1,
				},
				{
					name: "cheese",
					singular: "piece of cheese",
					plural: "pieces of cheese",
					name_ko: "치즈",
					post: 1,
					unit_ko: "조각",
					unit_post: 0,
				},
				{
					name: "macaroni_cheese",
					singular: "serving of macaroni and cheese",
					plural: "servings of macaroni and cheese",
					name_ko: "마카로니 치즈",
					post: 1,
					unit_ko: "인분",
					unit_post: 0,
				},
				{
					name: "pasta",
					singular: "serving of pasta",
					plural: "servings of pasta",
					name_ko: "파스타",
					post: 1,
					unit_ko: "인분",
					unit_post: 0,
				},
				{
					name: "cauliflower_cheese",
					singular: "serving of cauliflower cheese",
					plural: "servings of cauliflower cheese",
					name_ko: "콜리플라워 치즈",
					post: 1,
					unit_ko: "인분",
					unit_post: 0,
				},
				{
					name: "wheat",
					singular: "cup of wheat",
					plural: "cups of wheat",
					name_ko: "통밀",
					post: 2,
					unit_ko: "컵",
					unit_post: 0,
				},
				{
					name: "prawn_bisque",
					singular: "serving of prawn bisque",
					plural: "servings of prawn bisque",
					name_ko: "새우 비스크",
					post: 1,
					unit_ko: "인분",
					unit_post: 0,
				},
				{
					name: "cream",
					singular: "spoonful of cream",
					plural: "spoonfuls of cream",
					name_ko: "크림",
					post: 0,
					unit_ko: "스푼",
					unit_post: 0,
				},
				{
					name: "chelsea_bun",
					singular: "chelsea bun",
					plural: "chelsea buns",
					name_ko: "첼시 번빵",
					post: 0,
					unit_ko: "개",
					unit_post: 1,
				},
				{
					name: "honey",
					singular: "spoonful of honey",
					plural: "spoonfuls of honey",
					name_ko: "꿀",
					post: 2,
					unit_ko: "스푼",
					unit_post: 0,
				},
				{
					name: "butter",
					singular: "spoonful of butter",
					plural: "spoonfuls of butter",
					name_ko: "버터",
					post: 1,
					unit_ko: "스푼",
					unit_post: 0,
				},
				{
					name: "naan_bread",
					singular: "piece of naan bread",
					plural: "pieces of naan bread",
					name_ko: "난빵",
					post: 0,
					unit_ko: "조각",
					unit_post: 0,
				},
				{
					name: "pastry",
					singular: "piece of pastry",
					plural: "pieces of pastry",
					name_ko: "페이스트리",
					post: 1,
					unit_ko: "조각",
					unit_post: 0,
				},
				{
					name: "quiche",
					singular: "serving of quiche",
					plural: "servings of quiche",
					name_ko: "키시 파이",
					post: 1,
					unit_ko: "인분",
					unit_post: 0,
				},
				{
					name: "bacon",
					singular: "rasher of bacon",
					plural: "rashers of bacon",
					name_ko: "베이컨",
					post: 0,
					unit_ko: "줄",
					unit_post: 2,
				},
				{
					name: "mince_pie",
					singular: "mince pie",
					plural: "mince pies",
					name_ko: "갈아넣은 고기 파이",
					post: 1,
					unit_ko: "판",
					unit_post: 0,
				},
				{
					name: "sugar",
					singular: "spoonful of sugar",
					plural: "spoonfuls of sugar",
					name_ko: "설탕",
					post: 0,
					unit_ko: "스푼",
					unit_post: 0,
				},
				{
					name: "sausage_roll",
					singular: "sausage roll",
					plural: "sausage rolls",
					name_ko: "소시지롤",
					post: 2,
					unit_ko: "개",
					unit_post: 1,
				},
				{
					name: "sausage",
					singular: "sausage",
					plural: "sausages",
					name_ko: "소시지",
					post: 1,
					unit_ko: "개",
					unit_post: 1,
				},
				{
					name: "potato_pancake",
					singular: "potato pancake",
					plural: "potato pancakes",
					name_ko: "감자 팬케익",
					post: 0,
					unit_ko: "장",
					unit_post: 0,
				},
				{
					name: "onion_bhaji",
					singular: "onion bhaji",
					plural: "onion bhajis",
					name_ko: "양파 바지",
					post: 1,
					unit_ko: "인분",
					unit_post: 0,
				},
				{
					name: "chilli_pepper",
					singular: "chilli pepper",
					plural: "chilli peppers",
					name_ko: "고추",
					post: 1,
					unit_ko: "개",
					unit_post: 1,
				},
				{
					name: "samosa",
					singular: "samosa",
					plural: "samosas",
					name_ko: "사모사",
					post: 1,
					unit_ko: "인분",
					unit_post: 0,
				},
				{
					name: "sweet_and_sour_chicken",
					singular: "serving of sweet and sour chicken",
					plural: "servings of sweet and sour chicken",
					name_ko: "깐풍기",
					post: 1,
					unit_ko: "인분",
					unit_post: 0,
				},
				{
					name: "chicken",
					singular: "serving of chicken",
					plural: "servings of chicken",
					name_ko: "치킨",
					post: 0,
					unit_ko: "인분",
					unit_post: 0,
				},
				{
					name: "pepper",
					singular: "pepper",
					plural: "peppers",
					name_ko: "후추",
					post: 1,
					unit_ko: "개",
					unit_post: 1,
				},
				{
					name: "kedgeree",
					singular: "serving of kedgeree",
					plural: "servings of kedgeree",
					name_ko: "케저리",
					post: 1,
					unit_ko: "인분",
					unit_post: 0,
				},
				{
					name: "rice",
					singular: "cup of rice",
					plural: "cups of rice",
					name_ko: "쌀",
					post: 2,
					unit_ko: "컵",
					unit_post: 0,
				},
				{
					name: "haddock",
					singular: "haddock",
					plural: "haddock",
					name_ko: "해덕",
					post: 0,
					unit_ko: "마리",
					unit_post: 1,
				},
				{
					name: "honeyed_pork",
					singular: "serving of honeyed pork",
					plural: "servings of honeyed pork",
					name_ko: "꿀 바른 돼지고기",
					post: 1,
					unit_ko: "인분",
					unit_post: 0,
				},
				{
					name: "beef_wellington",
					singular: "serving of beef wellington",
					plural: "servings of beef wellington",
					name_ko: "소고기 웰링턴",
					post: 0,
					unit_ko: "인분",
					unit_post: 0,
				},
				{
					name: "salmon_wellington",
					singular: "serving of salmon wellington",
					plural: "servings of salmon wellington",
					name_ko: "연어 웰링턴",
					post: 0,
					unit_ko: "인분",
					unit_post: 0,
				},
				{
					name: "hamburger",
					singular: "hamburger",
					plural: "hamburgers",
					name_ko: "햄버거",
					post: 1,
					unit_ko: "개",
					unit_post: 1,
				},
				{
					name: "cheeseburger",
					singular: "cheeseburger",
					plural: "cheeseburgers",
					name_ko: "치즈버거",
					post: 1,
					unit_ko: "개",
					unit_post: 1,
				},
				{
					name: "chips",
					singular: "packet of chips",
					plural: "packets of chips",
					name_ko: "감자칩",
					post: 0,
					unit_ko: "봉지",
					unit_post: 1,
				},
				{
					name: "cheese_topped_trout",
					singular: "serving of cheese topped trout",
					plural: "servings of cheese topped trout",
					name_ko: "치즈로 뒤덮인 송어",
					post: 1,
					unit_ko: "인분",
					unit_post: 0,
				},
				{
					name: "salmon",
					singular: "salmon",
					plural: "salmon",
					name_ko: "연어",
					post: 1,
					unit_ko: "마리",
					unit_post: 1,
				},
				{
					name: "trout",
					singular: "trout",
					plural: "trout",
					name_ko: "송어",
					post: 1,
					unit_ko: "마리",
					unit_post: 1,
				},
				{
					name: "spaghetti_bolognese",
					singular: "serving of spaghetti bolognese",
					plural: "servings of spaghetti bolognese",
					name_ko: "볼로네제 스파게티",
					post: 1,
					unit_ko: "인분",
					unit_post: 0,
				},
				{
					name: "lasagne",
					singular: "serving of lasagne",
					plural: "servings of lasagne",
					name_ko: "라자냐",
					post: 1,
					unit_ko: "인분",
					unit_post: 0,
				},
				{
					name: "carbonara",
					singular: "serving of carbonara",
					plural: "servings of carbonara",
					name_ko: "까르보나라",
					post: 1,
					unit_ko: "인분",
					unit_post: 0,
				},
				{
					name: "chicken_tikka_masala",
					singular: "serving of chicken tikka masala",
					plural: "servings of chicken tikka masala",
					name_ko: "닭고기 티카 마살라",
					post: 1,
					unit_ko: "인분",
					unit_post: 0,
				},
				{
					name: "chilli_con_carne",
					singular: "serving of chilli con carne",
					plural: "servings of chilli con carne",
					name_ko: "칠리 콘 카르네",
					post: 1,
					unit_ko: "인분",
					unit_post: 0,
				},
				{
					name: "rich_biscuit",
					singular: "rich biscuit",
					plural: "rich biscuits",
					name_ko: "리치 비스킷",
					post: 0,
					unit_ko: "개",
					unit_post: 1,
				},
				{
					name: "shortbread",
					singular: "piece of shortbread",
					plural: "pieces of shortbread",
					name_ko: "쇼트브레드",
					post: 1,
					unit_ko: "조각",
					unit_post: 0,
				},
				{
					name: "melting_moment",
					singular: "melting moment",
					plural: "melting moments",
					name_ko: "멜팅 모먼트",
					post: 1,
					unit_ko: "개",
					unit_post: 1,
				},
				{
					name: "choc_chip_cookie",
					singular: "chocolate chip cookie",
					plural: "chocolate chip cookies",
					name_ko: "초콜렛 칩 쿠키",
					post: 1,
					unit_ko: "개",
					unit_post: 1,
				},
				{
					name: "cocoa_powder",
					singular: "cup of cocoa powder",
					plural: "cups of cocoa powder",
					name_ko: "코코아 가루",
					post: 1,
					unit_ko: "컵",
					unit_post: 0,
				},
				{
					name: "chocolate",
					singular: "slab of chocolate",
					plural: "slabs of chocolate",
					name_ko: "초콜렛",
					post: 0,
					unit_ko: "판",
					unit_post: 0,
				},
				{
					name: "jammie_dodger",
					singular: "jammie dodger",
					plural: "jammie dodgers",
					name_ko: "제이미 다저스",
					post: 1,
					unit_ko: "개",
					unit_post: 1,
				},
				{
					name: "jam",
					singular: "cup of jam",
					plural: "cups of jam",
					name_ko: "잼",
					post: 0,
					unit_ko: "컵",
					unit_post: 0,
				},
				{
					name: "apple_strudel",
					singular: "apple strudel",
					plural: "apple strudels",
					name_ko: "사과 슈트르델",
					post: 2,
					unit_ko: "인분",
					unit_post: 0,
				},
				{
					name: "soufflé",
					singular: "soufflé",
					plural: "soufflés",
					name_ko: "수플레",
					post: 1,
					unit_ko: "인분",
					unit_post: 0,
				},
				{
					name: "tart",
					singular: "tart",
					plural: "tarts",
					name_ko: "타르트",
					post: 1,
					unit_ko: "개",
					unit_post: 1,
				},
				{
					name: "lemon_meringue_pie",
					singular: "lemon meringue pie",
					plural: "lemon meringue pies",
					name_ko: "레몬 머랭 파이",
					post: 1,
					unit_ko: "판",
					unit_post: 0,
				},
				{
					name: "sponge_cake",
					singular: "sponge cake",
					plural: "sponge cakes",
					name_ko: "스폰지 케이크",
					post: 1,
					unit_ko: "인분",
					unit_post: 0,
				},
				{
					name: "swiss_roll",
					singular: "swiss roll",
					plural: "swiss rolls",
					name_ko: "롤케이크",
					post: 1,
					unit_ko: "인분",
					unit_post: 0,
				},
				{
					name: "scone",
					singular: "scone",
					plural: "scones",
					name_ko: "스콘",
					post: 0,
					unit_ko: "개",
					unit_post: 1,
				},
				{
					name: "brownie",
					singular: "brownie",
					plural: "brownies",
					name_ko: "브라우니",
					post: 1,
					unit_ko: "개",
					unit_post: 1,
				},
				{
					name: "carrot_cake",
					singular: "carrot cake",
					plural: "carrot cakes",
					name_ko: "당근 케이크",
					post: 1,
					unit_ko: "인분",
					unit_post: 0,
				},
				{
					name: "crème_brulee",
					singular: "pot of crème brulee",
					plural: "pots of crème brulee",
					name_ko: "크렘브릴레",
					post: 1,
					unit_ko: "그릇",
					unit_post: 0,
				},
				{
					name: "date",
					singular: "date",
					plural: "dates",
					name_ko: "대추",
					post: 1,
					unit_ko: "개",
					unit_post: 1,
				},
				{
					name: "sticky_toffee_pudding",
					singular: "sticky toffee pudding",
					plural: "sticky toffee puddings",
					name_ko: "끈적한 토피 푸딩",
					post: 0,
					unit_ko: "인분",
					unit_post: 0,
				},
				{
					name: "chicken_vindaloo",
					singular: "serving of chicken vindaloo",
					plural: "servings of chicken vindaloo",
					name_ko: "닭고기 빈달루",
					post: 1,
					unit_ko: "인분",
					unit_post: 0,
				},
				{
					name: "flapjack",
					singular: "flapjack square",
					plural: "flapjack squares",
					name_ko: "플랩잭",
					post: 0,
					unit_ko: "개",
					unit_post: 1,
				},
				{
					name: "cherry",
					singular: "cherry",
					plural: "cherries",
					name_ko: "체리",
					post: 1,
					unit_ko: "개",
					unit_post: 1,
				},
				{
					name: "belgian_bun",
					singular: "belgian bun",
					plural: "belgian buns",
					name_ko: "벨기에 번빵",
					post: 0,
					unit_ko: "개",
					unit_post: 1,
				},
				{
					name: "lime",
					singular: "lime",
					plural: "limes",
					name_ko: "라임",
					post: 0,
					unit_ko: "개",
					unit_post: 1,
				},
				{
					name: "linguine",
					singular: "serving of linguine",
					plural: "servings of linguine",
					name_ko: "링귀니",
					post: 1,
					unit_ko: "인분",
					unit_post: 0,
				},
				{
					name: "steak",
					singular: "serving of steak",
					plural: "servings of steak",
					name_ko: "스테이크",
					post: 1,
					unit_ko: "인분",
					unit_post: 0,
				},
				{
					name: "full_english_breakfast",
					singular: "full english breakfast",
					plural: "full english breakfasts",
					name_ko: "완전한 영국식 아침식사",
					post: 1,
					unit_ko: "인분",
					unit_post: 0,
				},
				{
					name: "apple_crumble",
					singular: "serving of apple crumble",
					plural: "servings of apple crumble",
					name_ko: "사과 크럼블",
					post: 1,
					unit_ko: "인분",
					unit_post: 0,
				},
				{
					name: "bakewell_tart",
					singular: "bakewell tart",
					plural: "bakewell tarts",
					name_ko: "베이크웰 타르트",
					post: 1,
					unit_ko: "개",
					unit_post: 1,
				},
				{
					name: "cod",
					singular: "cod",
					plural: "cod",
					name_ko: "대구",
					post: 1,
					unit_ko: "마리",
					unit_post: 1,
				},
				{
					name: "fish_and_chips",
					singular: "serving of fish and chips",
					plural: "servings of fish and chips",
					name_ko: "피쉬 앤 칩스",
					post: 1,
					unit_ko: "인분",
					unit_post: 0,
				},
				{
					name: "clam",
					singular: "clam",
					plural: "clams",
					name_ko: "조개",
					post: 1,
					unit_ko: "개",
					unit_post: 1,
				},
				{
					name: "clam_chowder",
					singular: "serving of clam chowder",
					plural: "servings of clam chowder",
					name_ko: "클램 차우더",
					post: 1,
					unit_ko: "인분",
					unit_post: 0,
				},
				{
					name: "cheese_and_crackers",
					singular: "serving of cheese and crackers",
					plural: "servings of cheese and crackers",
					name_ko: "치즈와 크래커",
					post: 1,
					unit_ko: "인분",
					unit_post: 0,
				},
				{
					name: "bangers_and_mash",
					singular: "serving of bangers and mash",
					plural: "servings of bangers and mash",
					name_ko: "소시지와 으깬 감자",
					post: 1,
					unit_ko: "인분",
					unit_post: 0,
				},
				{
					name: "yorkshire_pudding",
					singular: "yorkshire pudding",
					plural: "yorkshire puddings",
					name_ko: "요크셔 푸딩",
					post: 0,
					unit_ko: "인분",
					unit_post: 0,
				},
				{
					name: "stuffing",
					singular: "stuffing ball",
					plural: "stuffing balls",
					name_ko: "스터핑 볼",
					post: 2,
					unit_ko: "개",
					unit_post: 1,
				},
				{
					name: "roast_dinner",
					singular: "serving of roast dinner",
					plural: "servings of roast dinner",
					name_ko: "구운 고기 만찬",
					post: 0,
					unit_ko: "인분",
					unit_post: 0,
				},
				{
					name: "crumpet",
					singular: "crumpet",
					plural: "crumpets",
					name_ko: "크럼핏",
					post: 0,
					unit_ko: "개",
					unit_post: 1,
				},
				{
					name: "orange_juice",
					singular: "glass of orange juice",
					plural: "glasses of orange juice",
					name_ko: "오렌지 주스",
					post: 1,
					unit_ko: "잔",
					unit_post: 0,
				},
				{
					name: "lemonade",
					singular: "glass of lemonade",
					plural: "glasses of lemonade",
					name_ko: "레모네이드",
					post: 1,
					unit_ko: "잔",
					unit_post: 0,
				},
				{
					name: "banana_bread",
					singular: "loaf of banana bread",
					plural: "loaves of banana bread",
					name_ko: "바나나빵",
					post: 0,
					unit_ko: "덩이",
					unit_post: 1,
				},
				{
					name: "red_wine",
					singular: "bottle of red wine",
					plural: "bottles of red wine",
					name_ko: "레드 와인",
					post: 0,
					unit_ko: "병",
					unit_post: 0,
				},
				{
					name: "white_wine",
					singular: "bottle of white wine",
					plural: "bottles of white wine",
					name_ko: "화이트 와인",
					post: 0,
					unit_ko: "병",
					unit_post: 0,
				},
				{
					name: "poached_pear",
					singular: "poached pear",
					plural: "poached pears",
					name_ko: "데친 배",
					post: 1,
					unit_ko: "개",
					unit_post: 1,
				},
				{
					name: "peach_panzanella",
					singular: "serving of peach panzanella",
					plural: "servings of peach panzanella",
					name_ko: "복숭아 팡젤넬라",
					post: 1,
					unit_ko: "인분",
					unit_post: 0,
				},
				{
					name: "plum_pudding",
					singular: "serving of plum pudding",
					plural: "servings of plum pudding",
					name_ko: "자두 푸딩",
					post: 0,
					unit_ko: "인분",
					unit_post: 0,
				},
				{
					name: "spinach",
					singular: "spinach leaf",
					plural: "spinach leaves",
					name_ko: "시금치 잎",
					post: 0,
					unit_ko: "장",
					unit_post: 0,
				},
				{
					name: "salad",
					singular: "serving of salad",
					plural: "servings of salad",
					name_ko: "샐러드",
					post: 1,
					unit_ko: "인분",
					unit_post: 0,
				},
				{
					name: "arancini",
					singular: "arancini ball",
					plural: "arancini balls",
					name_ko: "아란치니 볼",
					post: 2,
					unit_ko: "개",
					unit_post: 1,
				},
				{
					name: "wolfbrew",
					singular: "bottle of wolfbrew",
					plural: "bottles of wolfbrew",
					name_ko: "울프브루",
					post: 1,
					unit_ko: "병",
					unit_post: 0,
				},
				{
					name: "ghostbrew",
					singular: "bottle of ghostbrew",
					plural: "bottles of ghostbrew",
					name_ko: "고스트브루",
					post: 1,
					unit_ko: "병",
					unit_post: 0,
				},
				{
					name: "beef",
					singular: "serving of beef",
					plural: "servings of beef",
					name_ko: "소고기",
					post: 1,
					unit_ko: "인분",
					unit_post: 0,
				},
				{
					name: "pork",
					singular: "serving of pork",
					plural: "servings of pork",
					name_ko: "돼지고기",
					post: 1,
					unit_ko: "인분",
					unit_post: 0,
				},
				{
					name: "cauliflower",
					singular: "cauliflower",
					plural: "cauliflowers",
					name_ko: "콜리플라워",
					post: 1,
					unit_ko: "송이",
					unit_post: 1,
				},
				{
					name: "oats",
					singular: "cup of oat",
					plural: "cups of oats",
					name_ko: "귀리",
					post: 1,
					unit_ko: "컵",
					unit_post: 0,
				},
				{
					name: "prawn",
					singular: "prawn",
					plural: "prawns",
					name_ko: "새우",
					post: 1,
					unit_ko: "마리",
					unit_post: 1,
				},
				{
					name: "omelette",
					singular: "omelette",
					plural: "omelettes",
					name_ko: "오믈렛",
					post: 0,
					unit_ko: "인분",
					unit_post: 0,
				},
				{
					name: "porridge",
					singular: "serving of porridge",
					plural: "servings of porridge",
					name_ko: "오트밀",
					post: 2,
					unit_ko: "인분",
					unit_post: 0,
				},
				{
					name: "turnip_soup",
					singular: "serving of turnip soup",
					plural: "servings of turnip soup",
					name_ko: "순무 수프",
					post: 1,
					unit_ko: "인분",
					unit_post: 0,
				},
		];
		
		let trPlantsNameIndex = {};
		let trPlantsSingularIndex = {};
		let trPlantsPluralIndex = {};
		for (const trPlantsData of setup.trPlants)
		{
			trPlantsNameIndex[trPlantsData.name] = trPlantsData;
			trPlantsSingularIndex[trPlantsData.singular] = trPlantsData;
			trPlantsPluralIndex[trPlantsData.plural] = trPlantsData;
		}
		setup.trPlants.nameIndex = Object.assign(trPlantsNameIndex, trPlantsSingularIndex, trPlantsPluralIndex);
	}
}
window.trinit_plants = trinit_plants;
