function init_trHandheld()
{
	setup.trClothes.handheld = [
		{
			index: 0,
			name: "naked",
			name_ko: "벗음",
			variable: "naked",
			post: 0,
			description: "naked",
		},
		{
			index: 1,
			name: "umbrella",
			name_ko: "우산",
			variable: "umbrella",
			post: 0,
			description: "비를 막아준다.",
		},
		{
			index: 2,
			name: "parasol",
			name_ko: "파라솔",
			variable: "parasol",
			post: 2,
			description: "비를 막아준다.",
		},
		{
			index: 3,
			name: "sweet lolita parasol",
			name_ko: "스위트 로리타 파라솔",
			variable: "parasolsweet",
			post: 2,
			description: "비를 막아준다.",
		},
		{
			index: 4,
			name: "paper parasol",
			name_ko: "종이 파라솔",
			variable: "parasolpaper",
			post: 2,
			description: "비를 막기 위해, 투명 코팅이 되어 있다.",
		},
		{
			index: 5,
			name: "purse",
			name_ko: "핸드백",
			variable: "purse",
			post: 0,
			description: "교과서를 들고 다니기 충분하다.",
		},
		{
			index: 6,
			name: "heart purse",
			name_ko: "하트 모양 핸드백",
			variable: "heartpurse",
			post: 0,
			description: "교과서를 들고 다니기 충분하다.",
		},
		{
			index: 7,
			name: "messenger bag",
			name_ko: "메신저백",
			variable: "messengerbag",
			post: 0,
			description: "교과서를 들고 다닐 때 유용하다.",
		},
		{
			index: 8,
			name: "backpack",
			name_ko: "책가방",
			variable: "backpack",
			post: 0,
			description: "교과서를 들고 다닐 때 유용하다.",
		},
		{
			index: 9,
			name: "paper fan",
			name_ko: "종이 부채",
			variable: "paperfan",
			post: 1,
			description: "당신을 시원하게 해준다.",
		},
		{
			index: 10,
			name: "milkshake",
			name_ko: "밀크셰이크",
			variable: "milkshake",
			post: 1,
			description: "맛있고 상쾌해진다.",
		},
		{
			index: 11,
			name: "cigarette",
			name_ko: "담배",
			variable: "cigarette",
			post: 1,
			description: "나쁜 습관은 그리 멋지게 보이지 않는다.",
		},
		{
			index: 12,
			name: "feather duster",
			name_ko: "깃털 먼지털이개",
			variable: "featherduster",
			post: 1,
			description: "청소할 때 귀여워 보인다.",
		},
		{
			index: 13,
			name: "pom poms",
			name_ko: "폼폼",
			variable: "pompoms",
			post: 0,
			description: "당신 팀의 승리를 응원하기 위한 것.",
		},
		{
			index: 14,
			name: "balloon",
			name_ko: "풍선",
			variable: "balloon",
			post: 0,
			description: "손에서 놓지 말자.",
		},
		{
			index: 15,
			name: "heart balloon",
			name_ko: "하트모양 풍선",
			variable: "balloonheart",
			post: 0,
			description: "손에서 놓지 말자.",
		},
		{
			index: 16,
			name: "bag of popcorn",
			name_ko: "팝콘 봉지",
			variable: "popcorn",
			post: 1,
			description: "아주 맛있다.",
		},
		{
			index: 17,
			name: "gingerbread man",
			name_ko: "사람 모양 생강 쿠키",
			variable: "gingerbread",
			post: 1,
			description: "도망쳐 도망쳐 도망쳐 가능한 한 빨리.",
		},
		{
			index: 18,
			name: "cup of lemonade",
			name_ko: "레모네이드 컵",
			variable: "lemonade",
			post: 0,
			description: "아주 맛있다.",
		},
		{
			index: 19,
			name: "hot drink",
			name_ko: "뜨거운 음료",
			variable: "cocoa",
			post: 1,
			description: "아주 맛있다.",
		},
		{
			index: 20,
			name: "mug",
			name_ko: "머그잔",
			variable: "mug",
			post: 0,
			description: "비어 있다.",
		},	
		{
			index: 21,
			name: "beer bottle",
			name_ko: "맥주병",
			variable: "beer bottle",
			post: 0,
			description: "술이다.",
		},	
		{
			index: 22,
			name: "mug of beer",
			name_ko: "맥주잔",
			variable: "beer mug",
			post: 0,
			description: "술이다.",
		},	
		{
			index: 23,
			name: "shot glass",
			name_ko: "양주잔",
			variable: "shotglass",
			post: 0,
			description: "술이다.",
		},	
		{
			index: 24,
			name: "wine glass",
			name_ko: "와인잔",
			variable: "wine",
			post: 0,
			description: "술이다.",
		},	
		{
			index: 25,
			name: "torch",
			name_ko: "횃불",
			variable: "torch",
			post: 2,
			description: "불타올라라, 베이비, 불타올라라.",
		},	
		{
			index: 26,
			name: "gym bag",
			name_ko: "체육복 가방",
			variable: "gymbag",
			post: 0,
			description: "교과서를 들고 다닐 때 유용하다, 교과서에서 체육복 양말 냄새가 나는 것을 신경쓰지 않는다면.",
		},	
		{
			index: 27,
			name: "cup of tea",
			name_ko: "홍차컵",
			variable: "tea",
			post: 0,
			description: "뜨겁다, 왜냐하면 아이스 티는 교양없는 자들이나 마시는 것이기 때문에.",
		},	
		{
			index: 28,
			name: "cup of coffee",
			name_ko: "커피컵",
			variable: "coffee",
			post: 0,
			description: "뜨겁다.",
		},	
		{
			index: 29,
			name: "forkful of salad",
			name_ko: "포크로 찍어놓은 샐러드",
			variable: "salad fork",
			post: 1,
			description: "토끼 밥이다.",
		},	
		{
			index: 30,
			name: "forkful of pancake",
			name_ko: "포크로 찍어놓은 팬케이크",
			variable: "pancake",
			post: 1,
			description: "시럽이 듬뿍 발라져 있다.",
		},	
		{
			index: 31,
			name: "forkful of pasta",
			name_ko: "포크로 찍어놓은 파스타",
			variable: "pasta",
			post: 1,
			description: "엄마가 집에 와서 스파게티를 만들어 줬을 때 필요하다. 당신에게 엄마가 있다면.",
		},	
		{
			index: 32,
			name: "fork",
			name_ko: "포크",
			variable: "fork",
			post: 1,
			description: "식기다.",
		},	
		{
			index: 33,
			name: "spoon",
			name_ko: "숟가락",
			variable: "spoon",
			post: 0,
			description: "식기다.",
		},	
		{
			index: 34,
			name: "cream bun",
			name_ko: "크림빵",
			variable: "cream bun",
			post: 0,
			description: "음란한 액체로 더럽혀지지 않았다. 아마도.",
		},	
		{
			index: 35,
			name: "ornate telescope",
			name_ko: "화려하게 장식된 망원경",
			variable: "ornatetelescope",
			post: 0,
			description: "놀랍게도 멋진 모습이다.",
		},	
		{
			index: 36,
			name: "hand of cards",
			name_ko: "카드 손패",
			variable: "cards",
			post: 1,
			description: "운이 좋을 것 같아요?",
		},
		{
			index: 37,
			name: "cane",
			name_ko: "지팡이",
			variable: "cane",
			post: 1,
			description: "가볍고 위엄있어 보인다.",
		},
		{
			index: 38,
			name: "forearm crutch",
			name_ko: "목발",
			variable: "crutch",
			post: 2,
			description: "보조도구가 보통 그래야 하듯이, 비싸지 않다.",
		},
		{
			index: 39,
			name: "bottle of sunscreen",
			name_ko: "선크림 통",
			variable: "sunscreen",
			post: 0,
			description: "하얗고 끈적거린다.",
		},
		{
			index: 40,
			name: "scrap of fabric",
			name_ko: "옷 조각",
			variable: "rag",
			post: 0,
			description: "당신의 옷 조각은 조각조각 찢어졌다!",
		},
		{
			index: 41,
			name: "pill bottle",
			name_ko: "약 통",
			variable: "pill bottle",
			post: 1,
			description: "약을 먹는 것을 잊지 말자.",
		},
		{
			index: 42,
			name: "paintbrush",
			name_ko: "그림붓",
			variable: "paintbrush",
			post: 0,
			description: "예술가적 성향이 있는 사람들을 위해.",
		},
		{
			index: 43,
			name: "net",
			name_ko: "그물",
			variable: "net",
			post: 2,
			description: "전부 다 잡고 말거야.",
		},
		{
			index: 44,
			name: "bottle of lube",
			name_ko: "윤활액 통",
			variable: "lube",
			post: 0,
			description: "젖으면 미끌미끌해진다.",
		},
		{
			index: 45,
			name: "breast pump",
			name_ko: "착유기",
			variable: "breast pump",
			post: 1,
			description: "당신의 집에서 편하게 신선한 우유를 생산한다.",
		},
		{
			index: 46,
			name: "can of hairspray",
			name_ko: "헤어 스프레이 캔",
			variable: "hairspray",
			post: 0,
			description: "꺼져라, 지독하게 헝클어진 머리카락이여, 내게서 꺼져라!",
		},
		{
			index: 47,
			name: "bottle of hair gel",
			name_ko: "헤어 젤 통",
			variable: "hairgel",
			post: 0,
			description: "꺼져라, 지독하게 헝클어진 머리카락이여, 내게서 꺼져라!",
		},
		{
			index: 48,
			name: "bottle of hair dye",
			name_ko: "염색약 통",
			variable: "hairdye",
			post: 0,
			description: "눈썹과 음모 전용.",
		},
		{
			index: 49,
			name: "dummy",
			name_ko: "공갈젖꼭지",
			variable: "dummy",
			post: 1,
			description: "아기용. 혹은 파티광용.",
		},
		{
			index: 50,
			name: "baby rattle",
			name_ko: "아기 딸랑이",
			variable: "rattle",
			post: 1,
			description: "엄마가 준 걸 흔들어 봐.",
		},
		{
			index: 51,
			name: "toy car",
			name_ko: "장난감 자동차",
			variable: "toycar",
			post: 1,
			description: "브렐카가 부웅 하고 가네.",
		},
		{
			index: 52,
			name: "stuffed bear",
			name_ko: "봉제인형",
			variable: "bear",
			post: 0,
			description: "부드럽고 껴안기 좋다",
		},
		{
			index: 53,
			name: "tray",
			name_ko: "쟁반",
			variable: "tray",
			post: 0,
			description: "절대 떨어뜨리지 마라.",
		},
		{
			index: 54,
			name: "trash bag",
			name_ko: "쓰레기 봉지",
			variable: "trash bag",
			post: 1,
			description: "그야말로 쓰레기.",
		},
		{
			index: 55,
			name: "can of spray paint",
			name_ko: "스프레이 페인트 캔",
			variable: "spray paint",
			post: 0,
			description: "비행 청소년들의 최애 도구.",
		},
		{
			index: 56,
			name: "bar of soap",
			name_ko: "비누",
			variable: "soap",
			post: 1,
			description: "둥둥둥.",
		},
		{
			index: 57,
			name: "love locket",
			name_ko: "러브 로켓",
			variable: "love locket",
			post: 0,
			description: "열면 사진을 넣는 자리가 드러난다.",
		},
		{
			index: 58,
			name: "textbook",
			name_ko: "교과서",
			variable: "textbook",
			post: 1,
			description: "지식으로 가득 차 있다.",
		},
		{
			index: 59,
			name: "textbook",
			name_ko: "교과서",
			variable: "open textbook",
			post: 1,
			description: "지식으로 가득 차 있다.",
		},
		{
			index: 60,
			name: "book",
			name_ko: "책",
			variable: "book",
			post: 0,
			description: "좋은 이야기들은 그 이야기들을 말해 줄 수 있는 자들에게 일어난다.",
		},
		{
			index: 61,
			name: "open book",
			name_ko: "책",
			variable: "open book",
			post: 0,
			description: "우리는 모두 마지막에는 이야기가 된다.",
		},
		{
			index: 62,
			name: "plate of sausage rolls",
			name_ko: "소시지롤을 담은 접시",
			variable: "sausage rolls",
			post: 1,
			description: "직접 만든 음식이다.",
		},
		{
			index: 63,
			name: "plate of scones",
			name_ko: "스콘을 담은 접시",
			variable: "scone plate",
			post: 1,
			description: "직접 만든 음식이다.",
		},
		{
			index: 64,
			name: "plate of biscuits",
			name_ko: "비스킷을 담은 접시",
			variable: "biscuit plate",
			post: 1,
			description: "직접 만든 음식이다.",
		},
		{
			index: 65,
			name: "soufflé",
			name_ko: "수플레",
			variable: "souffle",
			post: 1,
			description: "직접 만든 음식이다.",
		},
		{
			index: 66,
			name: "cake",
			name_ko: "케이크",
			variable: "cake",
			post: 1,
			description: "직접 만든 음식이다.",
		},
		{
			index: 67,
			name: "stuffing",
			name_ko: "속",
			variable: "stuffing",
			post: 0,
			description: "직접 만든 음식이다.",
		},
		{
			index: 68,
			name: "plate of sweet and sour chicken",
			name_ko: "깐풍기를 담은 접시",
			variable: "sweet and sour",
			post: 1,
			description: "직접 만든 음식이다.",
		},
		{
			index: 69,
			name: "swiss roll",
			name_ko: "롤케이크",
			variable: "swiss roll",
			post: 1,
			description: "직접 만든 음식이다.",
		},
		{
			index: 70,
			name: "blood lemon",
			name_ko: "블러드 레몬",
			variable: "blood lemon",
			post: 0,
			description: "레몬 훔치는 매춘부들에 의해 수확되었다.",
		},
		{
			index: 71,
			name: "lemon",
			name_ko: "레몬",
			variable: "lemon",
			post: 0,
			description: "레몬 훔치는 매춘부들에 의해 수확되었다.",
		},
		{
			index: 72,
			name: "apple",
			name_ko: "사과",
			variable: "apple",
			post: 1,
			description: "의사 하퍼를 멀리하도록 해 주지는 않는다.",
		},
		{
			index: 73,
			name: "banana",
			name_ko: "바나나",
			variable: "banana",
			post: 1,
			description: "아주 맛있다.",
		},
		{
			index: 74,
			name: "blackberry",
			name_ko: "블랙베리",
			variable: "blackberry",
			post: 1,
			description: "아주 맛있다.",
		},
		{
			index: 75,
			name: "orange",
			name_ko: "오렌지",
			variable: "orange",
			post: 1,
			description: "괴혈병 예방에 도움이 된다.",
		},
		{
			index: 76,
			name: "peach",
			name_ko: "복숭아",
			variable: "peach",
			post: 1,
			description: "악어 혓바닥을 조심하라.",
		},
		{
			index: 77,
			name: "pear",
			name_ko: "배",
			variable: "pear",
			post: 1,
			description: "아주 맛있다.",
		},
		{
			index: 78,
			name: "honeycomb",
			name_ko: "벌집",	/* 꿀? */
			variable: "honeycomb",
			post: 0,
			description: "끈적거리고 아주 맛있다.",
		},
		{
			index: 79,
			name: "strawberry",
			name_ko: "딸기",
			variable: "strawberry",
			post: 1,
			description: "아주 맛있다.",
		},
		{
			index: 80,
			name: "plum",
			name_ko: "자두",
			variable: "plum",
			post: 1,
			description: "즙이 많고 달콤하다.",
		},
		{
			index: 81,
			name: "bottle",
			name_ko: "병",
			variable: "milk bottle",
			post: 0,
			description: "바로 짠, 신선한 우유다.",
		},
		{
			index: 82,
			name: "salad",
			name_ko: "샐러드",
			variable: "salad",
			post: 1,
			description: "직접 만든 음식이다.",
		},
		{
			index: 83,
			name: "burger",
			name_ko: "버거",
			variable: "burger",
			post: 1,
			description: "직접 만든 음식이다.",
		},
		{
			index: 84,
			name: "plate of fish and chips",
			name_ko: "피쉬 앤 칩스를 담은 접시",
			variable: "fish and chips",
			post: 1,
			description: "직접 만든 음식이다.",
		},
		{
			index: 85,
			name: "roast dinner",
			name_ko: "구운 고기 만찬",
			variable: "roast dinner",
			post: 0,
			description: "직접 만든 음식이다.",
		},
		{
			index: 86,
			name: "mushroom",
			name_ko: "버섯",
			variable: "mushroom",
			post: 0,
			description: "재미있는 사람이다.",
		},
		{
			index: 87,
			name: "wolfshroom",
			name_ko: "늑대버섯",
			variable: "wolfshroom",
			post: 0,
			description: "늑대들이 허겁지겁 먹는다.",
		},
		{
			index: 88,
			name: "ghostshroom",
			name_ko: "유령버섯",
			variable: "ghostshroom",
			post: 0,
			description: "우리 주변의 균류이다.",
		},
		{
			index: 89,
			name: "pink mushroom",
			name_ko: "분홍색 버섯",
			variable: "pinkshroom",
			post: 0,
			description: "자연산 미약이다.",
		},
		{
			index: 90,
			name: "jar of pink fluid",
			name_ko: "분홍색 액체가 든 병",
			variable: "aphrodisiac jar",
			post: 0,
			description: "구현된 성욕.",
		},
		{
			index: 91,
			name: "condom",
			name_ko: "콘돔",
			variable: "condom",
			post: 0,
			description: "즙을 짜내기 전에 감싸두자.",
		},
		{
			index: 92,
			name: "black box",
			name_ko: "검은 상자",
			variable: "black box",
			post: 1,
			description: "랜드리가 부탁한 특별한 물건.",
		},
		{
			index: 93,
			name: "egg",
			name_ko: "알",
			variable: "egg",
			post: 2,
			description: "이 괴로운 시기에 당신에게 멋진 알을 드려도 될까요?",
		},
		{
			index: 94,
			name: "chocolate bar",
			name_ko: "초콜릿 바",
			variable: "chocolate bar",
			post: 1,
			description: "금색 티켓을 들어있지 않다.",
		},
		{
			index: 95,
			name: "bucket of candy",
			name_ko: "사탕 바구니",
			variable: "halloween",
			post: 1,
			description: "트릭-오어-트릿.",
		},
		{
			index: 96,
			name: "sucker",
			name_ko: "막대사탕",
			variable: "sucker",
			post: 0,
			description: "당신이 원하는 대로 핥아라.",
		},
		{
			index: 97,
			name: "travel cup",
			name_ko: "여행용 컵",
			variable: "travel cup",
			post: 0,
			description: "맛있다.",
		},
		{
			index: 98,
			name: "glass of juice",
			name_ko: "주스 컵",
			variable: "juice",
			post: 0,
			description: "맛있다.",
		},
		{
			index: 99,
			name: "key",
			name_ko: "열쇠",
			variable: "key",
			post: 1,
			description: "어떤 문들은 열리지 않은 채로 두는 게 낫다.",
		},
		{
			index: 100,
			name: "razor",
			name_ko: "면도기",
			variable: "razor",
			post: 1,
			description: "베이지 않도록 조심하라.",
		},
		{
			index: 101,
			name: "solo cup",
			name_ko: "일회용 컵",
			variable: "solo cup",
			post: 0,
			description: "파티 필수품이다.",
		},
		{
			index: 102,
			name: "salve jar",
			name_ko: "연고 병",
			variable: "salve",
			post: 0,
			description: "마사지 할 때 쓰면 좋다.",
		},
		{
			index: 103,
			name: "whisk",
			name_ko: "거품기",
			variable: "whisk",
			post: 1,
			description: "세계구급 크림빵을 만들기 위해.",
		},
		{
			index: 104,
			name: "candy box",
			name_ko: "사탕 상자",
			variable: "candy box",
			post: 1,
			description: "지나치게 달콤하다.",
		},
		{
			index: 105,
			name: "watering can",
			name_ko: "물뿌리개",
			variable: "watering can",
			post: 1,
			description: "마셔라, 이 목마른 개새끼들아.",
		},
		{
			index: 106,
			name: "broomstick",
			name_ko: "빗자루",
			variable: "witch broom",
			post: 1,
			description: "당신이 중력에 저항하게 해 주지는 않는다.",
		},
		{
			index: 107,
			name: "antique arrow",
			name_ko: "골동품 화살",
			variable: "arrow",
			post: 2,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 108,
			name: "antique artillery shell",
			name_ko: "골동품 포탄",
			variable: "artillery",
			post: 0,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 109,
			name: "antique bell",
			name_ko: "골동품 종",
			variable: "bell",
			post: 0,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 110,
			name: "antique brass statuette",
			name_ko: "골동품 황동상",
			variable: "brass statuette",
			post: 0,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 111,
			name: "antique bullet",
			name_ko: "골동품 총알",
			variable: "bullet",
			post: 2,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 112,
			name: "antique candlestick",
			name_ko: "골동품 양초",
			variable: "candlestick",
			post: 1,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 113,
			name: "antique cane",
			name_ko: "골동품 지팡이",
			variable: "sword cane",
			post: 1,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 114,
			name: "antique chastity belt",
			name_ko: "골동품 정조대",
			variable: "chastity",
			post: 1,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 115,
			name: "antique chocolate bar",
			name_ko: "골동품 초콜릿 바",
			variable: "chocolate",
			post: 1,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 116,
			name: "antique copper coin",
			name_ko: "골동품 구리 동전",
			variable: "copper coin",
			post: 0,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 117,
			name: "antique copper compass",
			name_ko: "골동품 구리 나침반",
			variable: "copper compass",
			post: 0,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 118,
			name: "antique copper ring",
			name_ko: "골동품 구리 반지",
			variable: "copper ring",
			post: 1,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 119,
			name: "antique coral ring",
			name_ko: "골동품 산호 반지",
			variable: "coral ring",
			post: 1,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 120,
			name: "antique crystal",
			name_ko: "골동품 수정",
			variable: "crystal",
			post: 0,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 121,
			name: "antique pink crystal",
			name_ko: "골동품 분홍색 수정",
			variable: "crystal pink",
			post: 0,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 122,
			name: "antique cup",
			name_ko: "골동품 컵",
			variable: "cup",
			post: 0,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 123,
			name: "antique cutlass",
			name_ko: "골동품 커틀라스 검",
			variable: "cutlass",
			post: 0,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 124,
			name: "antique dagger",
			name_ko: "골동품 단검",
			variable: "dagger",
			post: 0,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 125,
			name: "antique diamond",
			name_ko: "골동품 다이아몬드",
			variable: "diamond",
			post: 1,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 126,
			name: "antique medical aid",
			name_ko: "골동품 의료용 기구",
			variable: "antique dildo",
			post: 1,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 127,
			name: "antique disc",
			name_ko: "골동품 원반",
			variable: "disc",
			post: 0,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 128,
			name: "antique figurine",
			name_ko: "골동품 조각상",
			variable: "figurine",
			post: 0,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 129,
			name: "antique gem",
			name_ko: "골동품 보석",
			variable: "forest gem",
			post: 0,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 130,
			name: "antique gold brooch",
			name_ko: "골동품 금 브로치",
			variable: "gold brooch",
			post: 1,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 131,
			name: "antique gold coin",
			name_ko: "골동품 금 동전",
			variable: "gold coin",
			post: 0,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 132,
			name: "antique grenade",
			name_ko: "골동품 수류탄",
			variable: "grenade",
			post: 0,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 133,
			name: "antique horn",
			name_ko: "골동품 뿔",
			variable: "horn",
			post: 2,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 134,
			name: "antique hourglass",
			name_ko: "골동품 모래시계",
			variable: "hourglass",
			post: 1,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 135,
			name: "antique incense burner",
			name_ko: "골동품 향로",
			variable: "incense",
			post: 1,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 136,
			name: "antique island arrow",
			name_ko: "골동품 섬사람 화살",
			variable: "islander arrow",
			post: 2,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 137,
			name: "antique ivory box",
			name_ko: "골동품 상아 상자",
			variable: "ivory box",
			post: 1,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 138,
			name: "antique ivory statuette",
			name_ko: "골동품 상아 조각품",
			variable: "ivory statuette",
			post: 0,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 139,
			name: "antique map",
			name_ko: "골동품 지도",
			variable: "map",
			post: 1,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 140,
			name: "antique mine sign",
			name_ko: "골동품 광산 간판",
			variable: "bailey",
			post: 0,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 141,
			name: "antique rusted cutlass",
			name_ko: "골동품 녹슨 커틀라스 검",
			variable: "rusted cutlass",
			post: 0,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 142,
			name: "antique silver blade",
			name_ko: "골동품 은 칼날",
			variable: "silver blade",
			post: 2,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 143,
			name: "antique silver brooch",
			name_ko: "골동품 은 브로치",
			variable: "silver brooch",
			post: 1,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 144,
			name: "antique silver coin",
			name_ko: "골동품 은 동전",
			variable: "silver coin",
			post: 0,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 145,
			name: "antique silver compass",
			name_ko: "골동품 은 나침반",
			variable: "silver compass",
			post: 0,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 146,
			name: "antique silver crown",
			name_ko: "골동품 은 왕관",
			variable: "silver crown",
			post: 0,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 147,
			name: "antique silver dagger",
			name_ko: "골동품 은 단검",
			variable: "silver dagger",
			post: 0,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 148,
			name: "antique silver goblet",
			name_ko: "골동품 은 잔",
			variable: "silver goblet",
			post: 0,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 149,
			name: "antique silver mask",
			name_ko: "골동품 은 가면",
			variable: "silver mask",
			post: 0,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 150,
			name: "antique silver ring",
			name_ko: "골동품 은 반지",
			variable: "silver ring",
			post: 1,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 151,
			name: "antique tea caddy",
			name_ko: "골동품 찻잎 통",
			variable: "tea caddy",
			post: 0,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 152,
			name: "antique trilobite",
			name_ko: "골동품 삼엽충",
			variable: "trilobite",
			post: 0,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 153,
			name: "antique watch",
			name_ko: "골동품 시계",
			variable: "watch",
			post: 1,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 154,
			name: "antique gold compass",
			name_ko: "골동품 금 나침반",
			variable: "gold compass",
			post: 0,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 155,
			name: "antique gold necklace",
			name_ko: "골동품 황금 목걸이",
			variable: "gold necklace",
			post: 1,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 156,
			name: "antique gold ring",
			name_ko: "골동품 황금 반지",
			variable: "gold ring",
			post: 1,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 157,
			name: "antique fetish",
			name_ko: "골동품 숭배물",
			variable: "fetish",
			post: 2,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 158,
			name: "tube of parasite cream",
			name_ko: "기생충 기피 크림 튜브",
			variable: "parasite cream",
			post: 1,
			description: "기생충의 접근을 막는다.",
		},
		{
			index: 159,
			name: "truffle",
			name_ko: "송로버섯",
			variable: "truffle",
			post: 0,
			description: "퇴폐적이다.",
		},
		{
			index: 160,
			name: "antique islander mask",
			name_ko: "골동품 섬사람 가면",
			variable: "islander mask",
			post: 0,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 161,
			name: "antique ivory necklace",
			name_ko: "골동품 상아 목걸이",
			variable: "ivory necklace",
			post: 1,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 162,
			name: "antique stone talisman",
			name_ko: "골동품 돌 부적",
			variable: "stone talisman",
			post: 0,
			description: "박물관으로 가야 한다.",
		},
		{
			index: 163,
			name: "some lichen",
			name_ko: "이끼",
			variable: "lichen",
			post: 1,
			description: "과학을 위해서.",
		},
		{
			index: 164,
			name: "leaf",
			name_ko: "잎사귀",
			variable: "leaf",
			post: 1,
			description: "바삭거린다.",
		},
		{
			index: 165,
			name: "stuffed owl",
			name_ko: "올빼미 봉제인형",
			variable: "kylar owl",
			post: 0,
			description: "절대로 카메라는 아니다.",
		},
		{
			index: 166,
			name: "piece of junk",
			name_ko: "쓰레기",
			variable: "junk",
			post: 1,
			description: "쓸데 없다.",
		},
		{
			index: 167,
			name: "hoe",
			name_ko: "괭이",
			variable: "hoe",
			post: 1,
			description: "음란한 쪽을 의미하는 것이 아니다.",
		},
		{
			index: 168,
			name: "heavy duty torch",
			name_ko: "횃불",
			variable: "heavy duty torch",
			post: 2,
			description: "어둠을 밝혀준다.",
		},
		{
			index: 169,
			name: "hammer",
			name_ko: "해머",
			variable: "hammer",
			post: 1,
			description: "때가 되었다.",
		},
		{
			index: 170,
			name: "toy robot",
			name_ko: "장난감 로봇",
			variable: "robot",
			post: 0,
			description: "복고풍이다.",
		},
		{
			index: 171,
			name: "plate of burnt food",
			name_ko: "타버린 음식을 담은 접시",
			variable: "burnt",
			post: 1,
			description: "먹을 수 없다.",
		},
		{
			index: 172,
			name: "plate of unrecognisable slop",
			name_ko: "무언지 모를 음식물 쓰레기를 담은 접시",
			variable: "slop",
			post: 1,
			description: "먹을 수 없다.",
		},
		{
			index: 173,
			name: "plush clown",
			name_ko: "어릿광대 인형",
			variable: "clown toy",
			post: 0,
			description: "악의 없는 장난이거나, 무서운 장난이거나.",
		},
		{
			index: 174,
			name: "baby doll",
			name_ko: "아기 인형",
			variable: "baby doll",
			post: 0,
			description: "당신의 아기를 위한 아기.",
		},
		{
			index: 175,
			name: "net",
			name_ko: "그물",
			variable: "handheld net",
			post: 2,
			description: "전부 다 잡고 말거야.",
		},
	];
	
	/* pattern */
	setup.trClothes.handheld.pattern = {
		/* 24. wine glass*/
		"red": {name_ko : "레드 "},
		"white": {name_ko : "화이트 "},
		/* 52. stuffed bear */
		"bear": {name_ko : "곰 "},
		"mr teddy": {name_ko : "테디 씨 "},
		"mrs teddy": {name_ko : "테디 부인 "},
		/* 58. textbook, 59. open textbook */
		"English": {name_ko : "영어 "},
		"maths": {name_ko : "수학 "},
		"science": {name_ko : "과학 "},
		"history": {name_ko : "역사 "},
		/* 60. book */
		"scarlet": {name_ko : "진홍색 "},
		"olive": {name_ko : "올리브색 "},
		/* 61. open book */
		//"scarlet": {name_ko : "진홍색 "},
		//"olive": {name_ko : "올리브색 "},
		"storybook": {name_ko : "이야기"},
		/* 64. plate of biscuits */
		"jammie dodger": {name_ko : "제이미 다저스 "},
		"shortbread": {name_ko : "쇼트브레드 "},
		"rich": {name_ko : "두꺼운 "},
		"melting moment": {name_ko : "얇은 "},
		/* 66. cake */
		"carrot": {name_ko : "당근 "},
		"sponge": {name_ko : "스폰지 "},
		/* 81. bottle */
		"breast milk": {name_ko : "모유 "},
		"milk": {name_ko : "우유"},
		"semen": {name_ko : "정액 "},
		"baby": {name_ko : "젖"},
		/* 83. burger */
		"cheeseburger": {name_ko : "치즈"},
		"hamburger": {name_ko : "햄"},
		/* 93. egg */
		"bird": {name_ko : "새 "},
		"chicken": {name_ko : "닭 "},
		"hawk": {name_ko : "매 "},
		/* 97. travel cup */
		"cocoa": {name_ko : "코코아가 든 "},
		"cider": {name_ko : "사과주스가 든 "},
		/* 99. key */
		"standard": {name_ko : "일반 "},
		"iron": {name_ko : "철제 "},
		/* 169. hammer */
		"basic": {name_ko : "보통 "},
		"small": {name_ko : "작은 "},
		/* 172. plate of unrecognisable slop */
		"hallucinations": {name_ko : "환각을 일으키는 "},
		"slop": {name_ko : "음식물 찌꺼기 "},
		/* 187. box */
		"closed": {name_ko : "닫혀있는 "},
		"open": {name_ko : "열려있는 "},
		"creature": {name_ko : "생물 "},
		"aphrodisiac": {name_ko : "미약 "},
		"potato": {name_ko : "감자 "},
		/* 189. donut */
		"choco": {name_ko : "초코렛 "},
		"sprinkle": {name_ko : "설탕이 뿌려진 "},
		/* 197. tin of food */
		"beans": {name_ko : "삶은 콩 "},
		"custard": {name_ko : "커스터드 "},
		"tuna": {name_ko : "참치 "},
		/* 220. sandwich */
		"ham": {name_ko : "햄 "},
		"questionable": {name_ko : "미심쩍은 "},
		/* 226. phone */
		"corded": {name_ko : "유선"},
		"mobile": {name_ko : "무선"},
		/* 242. wine bottle */
		"corked": {name_ko : "코르크 마개를 한 "},
		//"open": {name_ko : "개봉된 "},
		"white_corked": {name_ko : "코르크 마개를 한 화이트 "},
		"white_open": {name_ko : "개봉된 화이트 "},
		/* 248. dog bowl */
		"full": {name_ko : "가득 찬 "},
		"empty": {name_ko : "비어있는 "},
		/* 250. jar of jam */
		"apple": {name_ko : "사과 "},
		"blackberry": {name_ko : "블랙베리 "},
		"lemon": {name_ko : "레몬 "},
		"orange": {name_ko : "오렌지 "},
		"peach": {name_ko : "복숭아 "},
		"pear": {name_ko : "배 "},
		"plum": {name_ko : "자두 "},
		"strawberry": {name_ko : "딸기 "},
		/* 260. tart */
		"general": {name_ko : "일반 "},
		"bakewell big": {name_ko : "커다란 베이크웰 "},
		"bakewell mini": {name_ko : "작은 베이크웰 "},
		/* 261. knife */
		"sharp": {name_ko : "날카로운 "},
		"chained": {name_ko : "사슬이 달려있는 "},
		/* 265. drink */
		"fizzy": {name_ko : "거품이 나는 "},
		"ghostbrew": {name_ko : "고스트브루 "},
		"wolfbrew": {name_ko : "울프브루 "},
		/* 272. bowl */
		"soup": {name_ko : "수프 "},
		"turnip soup": {name_ko : "순무 수프 "},
		"prawn bisque": {name_ko : "새우 비스크 "},
		"clam chowder": {name_ko : "클램 차우더 "},
		/* 274. thermos */
		//"closed": {name_ko : "닫혀있는 "},
		//"open": {name_ko : "열려있는 "},
		"hot": {name_ko : "뜨거운 "},
		/* 297. raw meat */
		"beef": {name_ko : "쇠"},
		"pork": {name_ko : "돼지"},
		"liver": {name_ko : "간 "},
		"chicken": {name_ko : "닭"},
		/* 301. biscuit */
		//"jammie dodger": {name_ko : "제이미 다저스 "},
		//"shortbread": {name_ko : "쇼트브레드 "},
		//"rich": {name_ko : "두꺼운 "},
		//"melting moment": {name_ko : "얇은 "},
		/* 305. raw fish */
		"cod": {name_ko : "대구 "},
		"haddock": {name_ko : "해덕 "},
		"salmon": {name_ko : "연어 "},
		"trout": {name_ko : "송어 "},
		/* 322. apple strudel */
		"strudel": {name_ko : "슈트르델"},
		"strudel sauce": {name_ko : "슈트르델 소스"},
		/* 328. slice of cake*/
		//"carrot": {name_ko : "당근 "},
		//"sponge": {name_ko : "스폰지 "},
		/* 330. cheese */
		"board": {name_ko : "판"},
		"slices": {name_ko : "조각"},
		"wedge": {name_ko : "쐐기모양 "},
		/* 332. buns */
		"belgian": {name_ko : "벨기에 "},
		"chelsea": {name_ko : "첼시 "},
		/* 333. bun */
		// "chelsea": {name_ko : "첼시 "},
		/* 347. slice of pie */
		// "lemon": {name_ko : "레몬 "},
		"mince": {name_ko : "갈아넣은 고기 "},
		/* 348. plate of pasta */
		"linguine": {name_ko : "링귀니 "},
		"noodles": {name_ko : "국수 "},
		"carbonara": {name_ko : "까르보나라 "},
		"bolognese": {name_ko : "볼로네제 "},
		/* 350. pie */
		//"lemon": {name_ko : "레몬 "},
		//"mince": {name_ko : "갈아넣은 고기 "},
		/* 352. omelette */
		"curse": {name_ko : "저주받은 "},
		"heart": {name_ko : "하트모양 "},
		"normal": {name_ko : "보통 "},
		"plain": {name_ko : "평범한 "},
		/* 355. pizza */
		"pie": {name_ko : "통"},
		"slice": {name_ko : "조각"},
		/* 356. pudding */
		//"plum": {name_ko : "자두 "},
		"yorkshire": {name_ko : "요크셔 "},
		"toffee": {name_ko : "토피 "},
	};
}
window.init_trHandheld = init_trHandheld;

